import pytest

from pathseq._parse_loose_path_sequence import (
    parse_path_sequence,
)
from pathseq import (
    FileNumSequence,
    NotASequenceError,
    PaddedRange,
    Ranges,
    RangesEndName,
    RangesInName,
    RangesStartName,
)


class TestPathSequence:
    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "#_file.exr",
                RangesStartName(
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "_",
                    "file",
                    (".exr",),
                ),
                id="#_file.exr",
            ),
            pytest.param(
                "1-10#_file.exr",
                RangesStartName(
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "_",
                    "file",
                    (".exr",),
                ),
                id="1-10#_file.exr",
            ),
            pytest.param(
                "1-10x2#_file.exr",
                RangesStartName(
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10x2"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "_",
                    "file",
                    (".exr",),
                ),
                id="1-10x2#_file.exr",
            ),
            pytest.param(
                "#file.exr",
                RangesStartName(
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    "file",
                    (".exr",),
                ),
                id="#file.exr",
            ),
            pytest.param(
                "#file.tar.gz",
                RangesStartName(
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    "file",
                    (".tar", ".gz"),
                ),
                id="#file.tar.gz",
            ),
        ],
    )
    def test_starts(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "#file",
                RangesStartName(
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    "file",
                    (),
                ),
                id="#file",
            ),
            pytest.param(
                "#_file",
                RangesStartName(
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "_",
                    "file",
                    (),
                ),
                id="#_file",
            ),
        ],
    )
    def test_starts_without_suffix(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "file.#.exr",
                RangesInName(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (".exr",),
                ),
                id="file.#.exr",
            ),
            pytest.param(
                "file.1-10#.exr",
                RangesInName(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (".exr",),
                ),
                id="file.1-10#.exr",
            ),
            pytest.param(
                "file.1-10x2#.exr",
                RangesInName(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10x2"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (".exr",),
                ),
                id="file.1-10x2#.exr",
            ),
            pytest.param(
                ".#.exr",
                RangesInName(
                    ".",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (".exr",),
                ),
                id=".#.exr",
            ),
            pytest.param(
                "#.tar.gz",
                RangesInName(
                    "",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (
                        ".tar",
                        ".gz",
                    ),
                ),
                id="#.tar.gz",
            ),
        ],
    )
    def test_in(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "texture.1011-1012####_1-3#.tex",
                RangesInName(
                    "texture",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1011-1012"),
                                "####",
                            ),
                            PaddedRange(
                                FileNumSequence.from_str("1-3"),
                                "#",
                            ),
                        ),
                        ("_",),
                    ),
                    "",
                    (".tex",),
                ),
                id="texture.1011-1012####_1-3#.tex",
            ),
        ],
    )
    def test_in_with_inter_range(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "#.exr",
                RangesInName(
                    "",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (".exr",),
                ),
                id="#.exr",
            ),
            pytest.param(
                "#.tar.gz",
                RangesInName(
                    "",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (".tar", ".gz"),
                ),
                id="#.tar.gz",
            ),
        ],
    )
    def test_in_without_stem(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "file.#.",
                RangesInName(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    ".",
                    (),
                ),
                id="file.#.",
            ),
            pytest.param(
                "file.#_",
                RangesInName(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "_",
                    (),
                ),
                id="file.#_",
            ),
            pytest.param(
                "file.#",
                RangesInName(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (),
                ),
                id="file.#",
            ),
            pytest.param(
                "file_#",
                RangesInName(
                    "file",
                    "_",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (),
                ),
                id="file_#",
            ),
            pytest.param(
                "file.#.exr.",
                RangesInName(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    ".exr.",
                    (),
                ),
                id="file.#.exr",
            ),
        ],
    )
    def test_in_without_suffix(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "#",
                RangesInName(
                    "",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                    (),
                ),
                id="#",
            ),
            pytest.param(
                "#_#",
                RangesInName(
                    "",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        ("_",),
                    ),
                    "",
                    (),
                ),
                id="#_#",
            ),
        ],
    )
    def test_in_without_stem_or_suffix(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "file.exr.#",
                RangesEndName(
                    "file",
                    (".exr",),
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                ),
                id="file.exr.#",
            ),
            pytest.param(
                "file.exr.1-10#",
                RangesEndName(
                    "file",
                    (".exr",),
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                ),
                id="file.exr.1-10#",
            ),
            pytest.param(
                "file.exr.1-10x2#",
                RangesEndName(
                    "file",
                    (".exr",),
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10x2"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                ),
                id="file.exr.1-10x2#",
            ),
            pytest.param(
                ".file.exr.#",
                RangesEndName(
                    ".file",
                    (".exr",),
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_file_nums([]),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    "",
                ),
                id=".file.exr.#",
            ),
        ],
    )
    def test_ends(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq",
        [
            "file",
            "dir",
            "file.exr",
            ".file.exr",
            ".file",
            "file.1.exr",
        ],
    )
    def test_not_a_sequence(self, seq):
        with pytest.raises(NotASequenceError):
            parse_path_sequence(seq)
