import pytest

from pathseq._parse_path_sequence import (
    parse_path_sequence,
)
from pathseq import (
    FileNumSequence,
    PaddedRange,
    ParseError,
    ParsedSequence,
    Ranges,
)


class TestPathSequence:
    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "file.#.exr",
                ParsedSequence(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str(""),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    (".exr",),
                ),
                id="file.#.exr",
            ),
            pytest.param(
                "file.1-10#.exr",
                ParsedSequence(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    (".exr",),
                ),
                id="file.1-10#.exr",
            ),
            pytest.param(
                "file.1-10x2#.exr",
                ParsedSequence(
                    "file",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1-10x2"),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    (".exr",),
                ),
                id="file.1-10x2#.exr",
            ),
            pytest.param(
                "textures.1011-1012<UDIM>_1-3#.tex",
                ParsedSequence(
                    "textures",
                    ".",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str("1011-1012"),
                                "<UDIM>",
                            ),
                            PaddedRange(
                                FileNumSequence.from_str("1-3"),
                                "#",
                            ),
                        ),
                        ("_",),
                    ),
                    (".tex",),
                ),
                id="textures.1011-1012<UDIM>_1-3#.tex",
            ),
        ],
    )
    def test_simple(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                ".#.exr",
                ParsedSequence(
                    ".",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str(""),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    (".exr",),
                ),
                id=".#.exr",
            ),
            pytest.param(
                ".hidden#.exr",
                ParsedSequence(
                    ".hidden",
                    "",
                    Ranges(
                        (
                            PaddedRange(
                                FileNumSequence.from_str(""),
                                "#",
                            ),
                        ),
                        (),
                    ),
                    (".exr",),
                ),
                id=".hidden#.exr",
            ),
        ],
    )
    def test_hidden_files(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected

    @pytest.mark.parametrize(
        "seq",
        [
            "#",
            "#.exr",
            "#.tar.gz",
            "#_#",
            "#_file",
            "#_file.exr",
            "#file",
            "#file.exr",
            "#file.tar.gz",
            ".file.exr.#",
            "1-10#_file.exr",
            "1-10x2#_file.exr",
            "file.#",
            "file.#.",
            "file.#.#",
            "file.#..exr",
            "file.#.exr.",
            "file.#.exr.",
            "file.#_",
            "file.1-10x0.5#",
            "file.1-10x0.5#.#",
            "file.exr.#",
            "file.exr.1-10#",
            "file.exr.1-10x2#",
            "file_#",
        ],
    )
    def test_parse_error(self, seq):
        with pytest.raises(ParseError):
            parse_path_sequence(seq)


class TestFilePath:
    @pytest.mark.parametrize(
        "seq,expected",
        [
            pytest.param(
                "",
                ParsedSequence(
                    "",
                    "",
                    Ranges(
                        (),
                        (),
                    ),
                    (),
                ),
                id="<empty>",
            ),
            pytest.param(
                "file",
                ParsedSequence(
                    "file",
                    "",
                    Ranges(
                        (),
                        (),
                    ),
                    (),
                ),
                id="file",
            ),
            pytest.param(
                "dir",
                ParsedSequence(
                    "dir",
                    "",
                    Ranges(
                        (),
                        (),
                    ),
                    (),
                ),
                id="dir",
            ),
            pytest.param(
                "file.exr",
                ParsedSequence(
                    "file",
                    "",
                    Ranges(
                        (),
                        (),
                    ),
                    (".exr",),
                ),
                id="file.exr",
            ),
            pytest.param(
                ".file.exr",
                ParsedSequence(
                    ".file",
                    "",
                    Ranges(
                        (),
                        (),
                    ),
                    (".exr",),
                ),
                id=".file.exr",
            ),
            pytest.param(
                ".file",
                ParsedSequence(
                    ".file",
                    "",
                    Ranges(
                        (),
                        (),
                    ),
                    (),
                ),
                id=".file",
            ),
            pytest.param(
                "file.1.exr",
                ParsedSequence(
                    "file",
                    "",
                    Ranges(
                        (),
                        (),
                    ),
                    (".1", ".exr"),
                ),
                id="file.1.exr",
            ),
        ],
    )
    def test_file_path(self, seq, expected):
        parsed = parse_path_sequence(seq)
        assert parsed == expected
